version: 2.1

jobs:

  build:
    docker:
      - image: circleci/python
        auth:
          username: $ESMF_DOCKER_USERNAME
          password: $ESMF_DOCKER_PASSWORD
    steps:
      - checkout:
      - run: echo "hello there"
